# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a596f56537500f0222a6c16a8fa6e38f8eaa5316b937934818b4b470b600fb2c3363c9ae00c2a07e544c3e957d347f9c1a3aae8dea4aeeff1e3f4e7426620f0

test:
  secret_key_base: 930165949007297ab268d6d823c30e49340f6e506ab92f4ae0e5d3ce021f0051171af27afa23cca502ffcfe7385a106f8c14ce3d81d2633f1a16d543776d38fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
